# 5uye-keak-g46i
version: '2'
services:
  web:
    image: odoo:14
    container_name: odoo_fridge
    command: odoo -u fridge
    depends_on:
      - db
    ports:
      - "8015:8069"
    restart: always
    volumes:
      - ../:/mnt/extra-addons

  db:
    image: postgres:10.0
    container_name: postgres_fridge
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
